[package]
name = "processor"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
database ={ path = "../../libs/database"}
kafka = { path = "../../libs/kafka"}
serde = { workspace = true }
serde_json = { workspace = true }